# Generated by Django 2.2.4 on 2020-06-14 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmiapp', '0003_auto_20200614_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmi',
            name='name',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
