# Generated by Django 2.2.4 on 2020-06-14 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmiapp', '0004_bmi_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bmi',
            old_name='height',
            new_name='height_in_cms',
        ),
    ]
