# Generated by Django 2.2.4 on 2020-06-25 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmiapp', '0005_auto_20200614_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmi',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
