# Generated by Django 2.2.4 on 2020-06-25 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmiapp', '0006_auto_20200626_0002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bmi',
            old_name='weight',
            new_name='weight_in_kgs',
        ),
    ]
